version: '3'

services:
  mydjango:
    build: ./mydjangoproject/
    command: python ./manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    volumes:
      - ./mydjangoproject/:/usr/app
    #depends_on:
    #  - db
  #db:
    #image: postgres
